# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Terry Cornelusse
# Config shared by the zsh modules and the `wts` CLI.
# Single source of truth for paths and binaries; the repo list is managed by `wts repo`.
# Machine-specific overrides (WTS_VENV, personal shell functions...) go in
# ~/.config/wts/config.sh, loaded first so its values win over the defaults below.
[ -f "$HOME/.config/wts/config.sh" ] && . "$HOME/.config/wts/config.sh"

WTS_ROOT="${WTS_ROOT:-$HOME}"
WTS_WORKTREE_DIR="${WTS_WORKTREE_DIR:-$HOME/worktrees}"
# Empty = the Default VS Code profile (the one the symlinks point to).
# Only set a name if you want a dedicated VS Code profile.
WTS_PROFILE="${WTS_PROFILE:-}"
# Name of the portable export file (backup / onboarding), generated by `wts profile build`.
WTS_PROFILE_FILE="${WTS_PROFILE_FILE:-worktree-station.code-profile}"

# "<name>:<default branch>:<type>[:<absolute path>]"
#   type = dbt | lookml | other   (drives the VS Code tasks and the wts commands)
#   path = optional; when absent, the clone is $WTS_ROOT/<name>
# The list lives in WTS_REPOS_FILE, one entry per line, managed by `wts repo`
# (or the extension's Repos panel). Without that file: no repo.
WTS_REPOS_FILE="${WTS_REPOS_FILE:-$HOME/.config/wts/repos}"
WTS_REPOS=()
if [ -f "$WTS_REPOS_FILE" ]; then
  WTS_REPOS=()
  while IFS= read -r _wts_line || [ -n "$_wts_line" ]; do
    case "$_wts_line" in ''|'#'*) continue ;; esac
    WTS_REPOS+=("$_wts_line")
  done < "$WTS_REPOS_FILE"
  unset _wts_line
fi

# Binaries: taken from WTS_VENV when set, otherwise from the PATH.
WTS_VENV="${WTS_VENV:-}"
WTS_DBT="${WTS_DBT:-${WTS_VENV:+$WTS_VENV/bin/}dbt}"
WTS_SQLFLUFF="${WTS_SQLFLUFF:-${WTS_VENV:+$WTS_VENV/bin/}sqlfluff}"
WTS_PYTHON="${WTS_PYTHON:-${WTS_VENV:+$WTS_VENV/bin/}python3}"

# dbt flags required by the running-dbt-commands skill
WTS_DBT_FLAGS=(--target dev --defer --state state/)
WTS_DBT_QUIET=(--quiet --warn-error-options '{"error": ["NoNodesForSelectionCriteria"]}')

# Table readers
wts_repo_name()   { printf '%s' "${1%%:*}"; }
wts_repo_branch() { local r="${1#*:}"; printf '%s' "${r%%:*}"; }
wts_repo_kind()   { local r="${1#*:}"; r="${r#*:}"; printf '%s' "${r%%:*}"; }
wts_repo_path()   { local r="${1#*:}"; r="${r#*:}"; case "$r" in *:*) printf '%s' "${r#*:}" ;; esac; }
wts_repo_dir()    { local p; p="$(wts_repo_path "$1")"; printf '%s' "${p:-$WTS_ROOT/${1%%:*}}"; }
